name: linux-musl

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


permissions:
  contents: write 

env:
  CARGO_TERM_COLOR: always
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:       
          - x86_64-unknown-linux-musl
          
          - aarch64-unknown-linux-musl
      
      fail-fast: false

    steps:

      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler libprotobuf-dev
          export PROTOC=/usr/bin/protoc


      - name: Install protoc
        uses: taiki-e/install-action@v2
        with:
          tool: protoc
          version: "3.25.3"

      - name: Check protoc
        run: protoc --version

        
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.92
          target: ${{ matrix.target }}
          override: true


      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}

      - name: Copy Release
        run: |
          ls -lah ./target/${{ matrix.target }}/release
          FULL_TARGET="${{ matrix.target }}"
          ARCH="${FULL_TARGET%%-*}"
          echo "Full target: $FULL_TARGET"
          echo "Arch: $ARCH"

          mkdir -p staging

          cp -r certs staging/certs
          cp -r payloads staging/payloads
          cp -r plugins staging/plugins
          
          cp "./target/${{ matrix.target }}/release/nps" "staging/nps.elf"
          tar -czf "release.${{ matrix.target }}.tar.gz" -C staging .

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: Release-latest
          files: |
            release.${{ matrix.target }}.tar.gz

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release.${{ matrix.target }}.tar.gz
