name: macos

on:
  push:
    tags:
      - 'v*'  

permissions:
  contents: write 
env:
  CARGO_TERM_COLOR: always
  
jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [macos-x86, macos-arm]
        include:

          - build: macos-x86
            os: macos-latest
            rust: 1.92
            target: x86_64-apple-darwin

          - build: macos-arm
            os: macos-latest
            rust: 1.92
            target: aarch64-apple-darwin
          
      fail-fast: false  

    steps:
      - name: Install protoc on macOS
        run: brew install protobuf

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
 
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.92
          profile: minimal
          override: true
          target: ${{ matrix.target }}
 
      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}
 
      - name: Copy Release
        run: |
          FULL_TARGET="${{ matrix.target }}"
          ARCH="${FULL_TARGET%%-*}"
          echo "Full target: $FULL_TARGET"
          echo "Arch: $ARCH"

          mkdir -p staging
          cp "./target/${{ matrix.target }}/release/nps" "staging/nps"
          tar -cf "release.${{ matrix.target }}.tar" -C staging .

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: Release-latest
          files: |
            release.${{ matrix.target }}.tar

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release.${{ matrix.target }}.tar