name: windows

on:
  push:
    tags:
      - 'v*'  


permissions:
  contents: write 
env:
  CARGO_TERM_COLOR: always
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:       
          - x86_64-pc-windows-gnu

      fail-fast: false
      
    steps:

      - name: Install protoc (host dependency)
        run: |
          PROTOC_VERSION="29.3"
          curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip
          sudo unzip -o protoc-${PROTOC_VERSION}-linux-x86_64.zip -d /usr/local
          echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install protobuf-compiler libprotobuf-dev
      
      - name: Install protoc
        uses: taiki-e/install-action@v2
        with:
          tool: protoc
          version: "3.25.3"
          
      - name: Check protoc
        run: protoc --version

      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.92
          target: ${{ matrix.target }}
          override: true


      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}

      - name: Copy Release
        run: |
          ls ./target/${{ matrix.target }}/release
          FULL_TARGET="${{ matrix.target }}"
          ARCH="${FULL_TARGET%%-*}"
          echo "Full target: $FULL_TARGET"
          echo "Arch: $ARCH"

          mkdir -p staging
          cp "./target/${{ matrix.target }}/release/nps.exe" "staging/nps.exe"
          tar -cf "release.${{ matrix.target }}.tar" -C staging .

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: Release-latest
          files: |
            release.${{ matrix.target }}.tar